- name: AWS EC2 instance launch
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Set up the security group and firewall rules
      ec2_group:
        name: ansible_ec2_security_group
        description: Rules that allow traffic on ports 22 and 80
        region: us-east-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0./0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch an EC2 instance
      ec2:
        key_name: id_rsa
        region: us-east-2
        instance_type: t2.micro
        image: ami-0dccf86d354af8ce3
        wait: yes
        wait_timeout: 500
        count: 1
        monitoring: no
        vpc_subnet_id: subnet-e8fc2aa4
        assign_public_ip: yes
        group: ansible_ec2_security_group
      register: ec2_out
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      wait_items: '{{ ec2_out.instances }}'
